language: node_js

node_js: stable

install:
  - npm install

script:
  - hexo cl
  - hexo g
  - hexo algolia

after_success:
  - cd public
  - git init
  - git config user.name "Kevinzjy"
  - git config user.email "kevinzjy1997@gmail.com"
  - git add .
  - git commit -m "Travis CI Auto Builder"
  - git push --force --quiet https://${GIT_TOKEN}@github.com/Kevinzjy/Kevinzjy.github.io.git master

branches:
  only:
    - source
